apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lodh
spec:
  replicas: 5
  selector:
    matchLabels:
      bank: lodh
  template:
    metadata:
      name: pod
      labels:
        bank: lodh
    spec:
      containers:
      - name: one
        image: redis
